### ISSUE TITLE
Looks like I can use it in my .net generic host

### ISSUE THREAD

**Issue by yww325** [GeeWee/BetterHostedServices#20]
### Question

Suggest maybe you could remove the asp.net keyword from the readme, I like the idea of doing less in starting the hosted service, and catching error in the start method.
I found it applies to my generic host console app

https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host

**Comment by GeeWee** [comment]
Hey! Clarified that it also works for non asp.net core projects. Thanks for the feedback!
